### ISSUE TITLE
Rev 1.0 hardware issues

### ISSUE THREAD

**Issue by CannaCardo** [sinara-hw/Magneto#1]
## Unused/ floating resources

- [x] IC23A missing from schematic, set as a GND follower to keep from floating
- [x] IC27B missing from schematic, used later in this issue
- [x] IC26C missing from schematic, short both inputs to GND
- [x] IC26D missing from schematic, short both inputs to GND
- [x] IC8A missing from schematic, short both inputs to GND
- [x] IC8C missing from schematic, used later in this issue
- [x] IC8D missing from schematic, used later in this issue

## Opamps with unmached input inpedances

- [x] IC40B inverting input connected directly to output, needs ~12k2 (10k + 2k2 can be used)
- [x] IC14A inverting input connected directly to output, needs 1k

## Diagnostic circuits

ADC dividers (R183/R184, R187/R185, R188/R186) are set to 10k/8k06 and cap out at 11.2V, while ~12V can be measured.
Choosing from values already in the project, 31k6/20k divider will allow up to 12.9V. 
- [x] R183, R187, R188 changed to 31k6 0.1%
- [x] R184, R185, R186 changed to 20k 0.1%
- [x] to leave filter unchanged, C46/C47/C48 should be changed from 1u to ~360n, 2x 100n should be fine

IC25C compares DAC setting and I_meas in opposing phases, causing V_limit_P and V_limit_N to always be on.
- [x] signals at R98/R107 should be crossed

Schematic for reference (v1.0 board)
<img src="https://github.com/user-attachments/assets/c804c117-c94c-46e4-a5c9-e37306626c79" width="560">
CH1 - R103 (I_meas), CH2 - R109 (DAC_OUT), +-1A 100Hz sine into a shorted output
<img src="https://github.com/user-attachments/assets/f781ad19-41f5-401e-abcf-cb166d19f142" width="560">
After crossing:
<img src="https://github.com/user-attachments/assets/10bc87bd-1ac1-4924-acd8-222124e5b770" width="560">

## DAC output:

When using internal DAC, the 0/5V DAC output is inverted, and scaled to -5/5V. With the output current proportional to -DAC_Vout, this works out to the output current being directly proportional to DAC code. 
When using external DAC, the input signal is not inverted.
- [x] R86 should be mounted
- [x] R86/R87 should be changed to 0.1% resistors (2k reused from R88/R89)

Schematic for reference (v1.0 board)
<img src="https://github.com/user-attachments/assets/0813b5fb-d30a-4f64-a1bd-da446a45aa41" width="800">

## Buck_Vout switch issues:

T1/T17 drivers create a 10k:10k divider (R134/R203 and R202/R204) placed at the transistor gate. With the lowest IC13 output voltage (4V) the T17 transistor does not fully open. Given the 20V G-S rating of [SI4425DDY-T1-GE3](https://www.vishay.com/docs/64732/si4425ddy.pdf)
- [x] both R203 and R204 can be changed to ~100R

<img src="https://github.com/sinara-hw/Magneto/assets/18137374/f6f4d817-a8d2-436a-ba06-0a95dfcfa9f2" width="560">

## Power stage

Last stage transistors (T19/T20 and T6/T9) are supplied from GND/Buck_Vout, and are driven by IC19 + T3/T5 and T8/T12 supplied from P15V0/N6V0. With load impedance too high for the set Buck_Vout voltage (especially when output is disconnected) IC19 tends to go to the very rails, which causes either T3/T12 or T5/T8 to turn on very hard, and causes T19/T9 or T20/T6 to work as a base-collector diode - burning a lot of power and locking itself in this state at one of the rails. This either raises the Buck_Vout and/or raises the N6V0 rail, pulling PG low.

Inserting series diodes at outer stage collectors (with added capacitance after the diodes, at the collectors) fixes this issue, but burns a lot of power at high currents and shortens the output voltage range.

At the same time, when driving high output currents (during tests: more than +-3A range), T3/T8 seem to take a lot of current (based on thermal camera), causing  IC49 to eventually pull PG low and disable the P15V0 rail. This affects the opamps in diagnostics section, and falsely raises PWR_lim diode.

IC19 and T3/T5/T8/T12 can be potentially swapped from P15V0/N6V0 to GND/Buck_Vout, to prohibit this from happening and to not add any additional heat generators to the board (some output voltage range will be lost as well). This would require:
- increasing Buck_Vout values from 4V/8V/10V/12V above 4.5V (minimal [OPA2197IDGKR](https://www.ti.com/lit/ds/symlink/opa2197.pdf?ts=1720971420175&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FOPA2197%253Fbm-verify%253DAAQAAAAJ_____0f-ujbNA1rdirgZf-mxRl4JFmvbUB2lABlfI91t-tY9VYXoXcBNUTrGx9JE18sdtz3cSHAiUt2FHPEQlavL9ADwGlYBcp-ijYdMp_BE89lTVgq5brfCV9LirQdioDaKYsUcIh49iVVCfj4BQB-BgpXfbrceAXiMj260jlYibH12yKsoJxqcZELIiTNG00pnyNxNUVijADZvmlUL2a_FdafuSJfwOxu1lHgntQ1N4JExBZJCCEOi_Q7dNxMHh7pndm-1LMlNwZeRRxHbuTII2rTOyK-PCQIO978AdzKf9sxF) supply)
- limiting IC14B output to stay within 0-Buck_Vout

IC14Bs output is always equal to +-5V (Vin=set current) + Buck_Vout/2 (Ref). Assuming that lowest Buck_Vout value is changed from 4V to 5V, this means that in worst case it ranges from -2.5V to 7.5V at 0/5V IC19 supply. If Vin were to be initially divided from +-5V to +-2V, this would give at least a 0.5V headroom from each rail - this can be later corrected by increasing the gain (RN1A/RN1D = 20k, RN1B/RN1C = 1k):

$Iout = -1k/20k/R19 * Vin$

With Vin scaled by $2/5$, R19 (0.05R) should be decreased by $5/2$ to 0.02R (with the same RN1 ratio), or decreased by $4/5$ to 0.04R (RN1 ratio changed to 10:1)
<img src="https://github.com/user-attachments/assets/422e425a-72e2-41fa-a147-f56c9eca8a21" width="560">

Schematic for reference (v1.0 board):
<img src="https://github.com/user-attachments/assets/2bc0e246-8ca9-4faa-b701-600e1fe8f96a" width="800">

## PG signal

There are several issues with the PG signal. For reference: it is asserted by IC49 (N6V0/P15V0), IC21 (P5V4A), IC13 (Buck_Vout), is pulled up by R123 to P3V3_MP, and it sets the LD5 LED, resets the IC36 IO expander, clears DAC output and disables the 5V reference voltage.

- [x] no pullups/pulldowns at IC36 IO expander outputs (Ref_Sel_0, Ref_Sel_1, VSEL_0, VSEL_1), IOs set as inputs by default - this leaves IC13 output (Buck_Vout) in an undefined state (feedback controlled by VSEL_0/VSEL_1) and pulls PG low. It would be best to default at the lowest IC13 output voltage (all IC36 outputs high). 
<img src="https://github.com/sinara-hw/Magneto/assets/18137374/28fb12f6-1a13-498b-84c1-fd304a33d00a" width="560">  

- [x] when using internal DAC, a PG drop will cause the DAC output to reset back to 0x0000 - which corresponds to -5A at the output driver. It would probably be better to stay at whatever setting pulled PG low. A better safety mechanism would be to disable the Buck_Vout rail - included in one of further fixes.

- [x] a low PG will disable the internal 5V reference (IC11/IC20), used to derive various other voltages: the DAC output, derived 2/4/5/6V reference for the power stage, and derived references in the diagnostics ADC circuitry. This will cause ADC diagnostics to be lost along with power/voltage limit signals. Same as with the DAC, it would probably be better to leave it enabled.

- [x] VSEL_0/1 signals set Buck_Vout voltage to 4/8/10/12 V. When set to 12V (VSEL_0 = 0, VSEL_1 = 0), IC13 is disabled (RUN low), and T1/T17 are set to bypass it (T1 on, T17 off). Tying RUN pin low also pulls PG output low (internally in IC13). When hard-wired high, PG is also pulled low as the buck converter is not able to generate a 12V output (set via R76) due to minimal dropout. When set for a lower output voltage, P12V0 back-feeds via the parasitic diode in T17 and raises VOUT voltage - also pulling PG low. For other Buck_Vout voltages, during transition IC13 output is momentarily not matched with the connected feedback resistors - causing PG to drop and reset IC36 IO expander, reverting the change. 

Schematic for reference (v1.0 board):
<img src="https://github.com/user-attachments/assets/1e1bc6f1-9f0d-45a2-a8bd-7c56f90ee2d2" width="800">

CH1 - PG signal, CH2 - Buck_Vout power rail, IC36 reset forced high
<img src="https://github.com/sinara-hw/Magneto/assets/18137374/7fbbc516-255a-4741-a567-da1c26d709bd" width="560">  
With partial solution (IC13 disconnected from PG at 12V output)
<img src="https://github.com/sinara-hw/Magneto/assets/18137374/5e47d801-d609-4eff-b57b-fe73182b3740" width="560"> 

Those issues can be fixed by disconnecting PG net from IC13 when configured for a 12V output, and by adding an ignore window (after changing VSEL_0/1) with a duration longer than ~150ms (too long for a realistic RC filter). IC8/IC26/IC27 (quad OR, dual monostable multivibrator) have unused resources in the mounted packages, and were used for the solution. 

<img src="https://github.com/user-attachments/assets/c5a09339-06f8-46a1-b3c1-676e9e094332" width="800">

<img src="https://github.com/sinara-hw/Magneto/assets/18137374/00e4c906-2558-4405-8306-569eaff13b17" width="560">

## BOM Count reduction

Many passives are only used once, many components have close values, and several values are unnecessarily used in different packages.
The board is not densly populated, it will be easy to correct the below.

Reductions in resistor values:
- [x] R210 100k (10k/100k divider) changed to 10k (R200/R215 10k changed to 1k)
- [x] R207 47k (3k3/47k divider) replaced with (3k/) 33k+10k
- [x] R135 31k6 (10k/31k6 divider) replaced with (24k/)75k
- [ ] R11, R142 2x27k replaced with 24k+20k+10k
- [x] R76, R168, R190 replaced 20k with 2x 10k
- [x] R42 13k replaced with 10k + 3k
- [x] R136 10k (10k/31k6 divider) replaced with 24k(/75k)
- [x] R105 10k 0.1% replaced with 20k 0.1% || 20k 0.1%
- [x] R183, R187, R188 10k 0.1% ADC divider (10k/8k06) - changed to 31k6(/20k) 0.1%
- [x] 140, 141 10k with invalid part number (1k) changed to valid 0402 10k
- [x] R184, R185, R186 8k06 ADC divider (10k/8k06) - changed to (31k6/)20k 0.1%
- [x] R93 7k5 replaced with 10k || (10k+20k)
- [x] R139 5k6 pullup replaced with 3k+2k7
- [x] R189 0603 5k1  replaced with 10k || 10k
- [x] R170, R194 0402 5k1 replaced with 10k || 10k
- [x] R41 changed from 0603 4k99 to 0603 10k||10k
- [x] R163 0402 4k7 replaced with 0603
- [x] R100 3k3 (3k3/47k divider) replaced with 3k (/33k+10k)
- [x] R1, R4 0402 2k2 changed to 0603 2k2
- [x] R48, R88, R89 2k 0.1% replaced with 2x series 1k 0.1%
- [x] R58, R143 1k6 || 1k6 replaced with 1k3 || 2k2
- [x] R92 1k5 replaced with 3k || 3k
- [x] R17 (series LDAC resistor at driver) changed from 1k to 100R 0402
- [x] R22, R87, R182 changed from 1k 0402 to 1k 0603 0.1%
- [x] R6, R9, R20, R28, R29, R118, R119, R121 (series FP LED) resistors changed from 220 to 200R
- [x] R33 (series IC36 reset resistor) changed from 220 to 200R
- [x] R5 0402 200R replaced with 0603
- [x] R79, R81, R83, R85 replaced with 200R || 200R
- [x] R164 10R replaced with 22R || 22R
- [x] R129, R130 0R FP grounding changed from 0603 to 0805 

Summary of all R values in the board (crossed lines can be removed):

| Value     | Case     | Tolerance | Count | Designators | Comment |
| --------- |:--------:|:---------:|:-----:|:-----------:|:-------:|
| 4M7       | 0805     |        1% |     4 |             |         |
| 1M        | 0603     |        1% |     3 |             |         |
| 160k      | 0603     |        1% |     1 | R40         | Part of feedback resistance, total required 165k (series 5k)         |
| ~~100k~~  | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R210~~    | Part of a 10k/100k divider, changed to 1k/10k        |
| 80k6      | 0603     |      0.1% |     2 | R212, R213  |         |
| 75k       | 0603     |        1% | ~~1~~ 2 | R32         | Part of feedback resistance, total required 79k7 (series 4k7)          |
| 68k       | 0603     |        1% |     1 | R21         | Part of feedback resistance, total required 72k3 (series 4k3)        |
| ~~47k~~   | ~~0402~~ |    ~~1%~~ | ~~1~~ | ~~R207~~    | Part of a voltage divider, 3k3/47k, replaced with 3k/(33k+10k)  |
| 33k       | 0603     |        1% | ~~4~~ 5 | R39, R77, R205, R217            |         |
| 31k6 | 0603 |  0.1% | ~~1~~ 3 | ~~R135~~    | Part of a voltage divider, 10k/31k6, replaced with (24k/)75k       |
| 27k       | 0603     |        1% | 2     | R101, R117  |         |
| ~~27k~~   | ~~0402~~ |    ~~1%~~ | ~~2~~ | ~~R11, R142~~ | Part of feedback resistance, total required 54k (2x 27k), replaced with 24k+20k+10k |
| 24k       | 0603     |        1% | ~~1~~ 3 | R75         | Part of feedback resistance, total required 26k7 (series 2k7)         |
| 20k       | 0603     |      0.1% | ~~7~~ 13 | -           |  |   
| ~~20k~~   | ~~0603~~ |    ~~1%~~ | ~~3~~ | ~~R76, R168, R190~~ | Replaced with 2x 10k 0603       |
| ~~13k~~       | ~~0402~~     |     ~~1%~~ |   ~~1~~ | ~~R42~~       | series P15V0 LED resistor        |
| 10k       | 0402     |        1% | ~~19~~ 24 | ~~R136~~, (...)  | Part of a voltage divider, 10k/31k6, replaced with 24k(/75k) |
| 10k       | 0603     |        1% | ~~34~~ 50 |             |         |
| ~~10k~~   | ~~0603~~ |  ~~0.1%~~ | ~~4~~ | ~~R105, R183, R187, R188~~ | ADC divider (10k/8k06) - changed to 31k6(/20k) 0.1%   |
| ~~10k~~   | ~~0402~~ |    ~~1%~~ | ~~2~~ | ~~140, 141~~ | INVALID PART NUMBER, changed to valid 0402 10k        |
| ~~8k06~~  | ~~0603~~ |  ~~0.1%~~ | ~~3~~ | ~~R184, R185, R186~~ | ADC divider (10k/8k06) - changed to (31k6/)20k 0.1%       |
| ~~7k5~~   | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R93~~     | replaced with 10k \|\| (10k+20k) |
| ~~5k6~~   | ~~0402~~ |    ~~1%~~ | ~~1~~ | ~~R139~~    | Pullup, replaced with 3k+2k7      |
| ~~5k1~~   | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R189~~    | Replaced with 10k \|\| 10k     |
| ~~5k1~~   | ~~0402~~ |    ~~1%~~ | ~~2~~ | ~~R170, R194~~    | Replaced with 10k \|\| 10k     |
| ~~4k99~~  | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R41~~     | Replaced with 2x parallel 10k        |
| 4k7       | 0603     |        1% | ~~1~~ 2 | R30         | Part of feedback resistance, total required 79k7 (series 75k)          |
| ~~4k7~~   | ~~0402~~ |    ~~1%~~ | ~~1~~ | ~~R163~~    | series N6V0 LED resistor, replaced with 0603        |
| 4k3       | 0603     |        1% |     1 | R26         | Part of feedback resistance, total required 72k3 (series 68k)          |
| 3k9       | 0603     |        1% |     1 | R5          |         |
| ~~3k3~~   | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R100~~    | Part of a voltage divider, 3k3/47k, replaced with 3k/(33k+10k)        |
| 3k        | 0603     |        1% | ~~4~~ 9 |             |         |
| 2k7       | 0603     |        1% | ~~6~~ 7 |             |         |
| 2k49      | 0603     |      0.1% |     1 | R99         |         |
| 2k2       | 0603     |        1% | ~~3~~ 6 |           |         |
| ~~2k2~~   | ~~0402~~ |    ~~1%~~ | ~~2~~ | ~~R1, R4~~  | Replaced with 0603 2k2        |
| ~~2k~~    | ~~0603~~ | ~~0.1%~~  | ~~3~~ | ~~R48, R88, R89~~  | Replaced with 2x 1k 0.1%        |
| 1k8       | 0402     |        1% |     1 | R56         |         |
| ~~1k6~~   | ~~0402~~ |    ~~1%~~ | ~~2~~ | ~~R58, R143~~ | Placed in parallel to get 800R, replaced with 1k3\|\|2k2         |
| ~~1k5~~   | ~~0603~~ |    ~~1%~~ | ~~1~~ | ~~R92~~     | Replaced with 3k \|\| 3k        |
| 1k3       | 0603     |        1% | ~~1~~ 2 | R218      |         |
| 1k        | 0603     |      0.1% | ~~6~~ 17   |             |         |
| ~~1k~~    | ~~0402~~ |    ~~1%~~ | ~~4~~ | ~~R17, R22, R87, R182~~ | R17 changed to 100R, others to 0603 case        |
| ~~220~~   | ~~0603~~ |    ~~1%~~ | ~~9~~ | ~~R6, R9, R20, R28, R29, R33, R118, R119, R121~~ | Series LED resistors        |
| 200       | 0603     |        1% | ~~2~~ 20 |             |         |
| ~~200~~   | ~~0402~~ |    ~~1%~~ | ~~1~~ | ~~R5~~      | Replaced with 0603 200R         |
| 110       | 0603     |        1% | 1     | R176            |         |
| ~~100~~   | ~~0603~~ |    ~~1%~~ | ~~4~~ | ~~R79, R81, R83, R85~~  | replace with 2x \|\| 200R        |
| 100       | 0402     |        1% | ~~17~~ 18 |             |         |
| 22        | 0402     |        1% | ~~5~~ 7 |             |         |
| ~~10~~    | ~~0402~~ |    ~~1%~~ | ~~1~~ | ~~R164~~    | Replaced with 22R \|\| 22R        |
| 0R05      | 2512     |      0.1% |     1 | R19         |         |
| 0         | 0805     |           | ~~1~~ 3 | R149        |         |
| ~~0~~     | ~~0603~~ |           | ~~2~~ | ~~R129, R130~~ | FP Grounding        |
| 0         | 0402     |           |    27 |             |         |

Total of 25 positions removed

Reductions in capacitor values:
- [x] C67 45pF can be replaced by 3x 15pF in parallel
- [x] merged 2 distinct 0402 100n 16V decoupling capacitors - PN difference in X5R vs X7R (eg C3 vs C23)
- [x] C71, C81 0402 16V 1uF changed to 0603 25V 1uF
- [x] C14 1206 50V 1uF changed to 0603 25V 1uF
- [x] 0603 16V 1uF changed to 0603 25V 1uF
- [x] C167 changed from 0603 10V 10uF to 0603 16V 10uF
- [x] C39, C40 changed from 0805 16V 10uF to 0603 16V 10uF
- [x] C79 changed from 0603 6.3V 22uF to 0805 16V 22uF

Summary of all C values in the board (crossed lines can be removed):

| Value     | Case     | Tolerance/ Voltage | Count | Designators | Comment |
| --------- |:--------:|:---------:|:-----:|:-----------:|:-------:|
| 220uF | 8x6.2mm | 20% / 16V | 1 | C98 | electrolytic |
| 47uF | 1206 | 20% / 25V | 4 |  | X5R |
| 47uF | 6032-28 | 10% / 16V | 2 | C503, C504 | tantalum |
| 22uF | 0805 | 10% / 16V | ~~6~~ 7 | | X5R |
| 22uF | 3528-21 | 10% / 10V | 1 | C91 | tantalum |
| ~~22uF~~ | ~~0603~~ | ~~20% / 6.3V~~ | ~~1~~ | ~~C79~~ | ~~X5R~~ |
| 10uF | 0805 | 10% / 25V | 18 | | X5R |
| 10uF | 3216-18 | 20% / 16V | 9 | | tantalum |
| ~~10uF~~ | ~~0805~~ | ~~10% / 16V~~ | ~~2~~ | ~~ C39, C40~~ | ~~X5R~~ |
| 10uF | 0603 | 20% / 16V | ~~2~~ 5 |  C50, C72 | X5R |
| ~~10uF~~ | ~~0603~~ | ~~10% / 10V~~ | ~~1~~ | ~~C167~~ | ~~X5R~~ |
| ~~1uF~~  | ~~1206~~ | ~~10% / 50V~~ | ~~1~~ |  ~~C14~~ | ~~X7R~~ |
| 1uF  | 0603 | 10% / 25V | ~~8~~ 18 |  | X7R |
| ~~1uF~~  | ~~0603~~ | ~~10% / 16V~~ | ~~7~~ |  | ~~X7R~~ |
| ~~1uF~~  | ~~0402~~ | ~~10% / 16V~~ | ~~2~~ | ~~C71, C81~~ | ~~X5R~~ |
| 100nF | 0402 | 10% / 16V | ~~41~~ 54 |  | X5R |
| ~~100nF~~ | ~~0402~~ | ~~10% / 16V~~ | ~~13~~ |  | ~~X7R~~ |
| 3.3nF | 0402 | 10% / 50V | 2 | C441, C442 | X7R |
| 100pF | 0603 | 1% / 50V | 4 | | NP0 |
| ~~47pF~~ | ~~0402~~ | ~~1% / 50V~~ | ~~1~~ | ~~C67~~ | ~~NP0~~ |
| 15pF | 0603 | 5% / 50V | ~~4~~7 | | NP0 |
| 10pF | 0402 | 5% / 50V | 1 | C63 | NP0 |

Total of 8 positions removed

Other BOM count reductions:
- [x] T4 uses BSH103 N-MOS, while BSS138 N-MOS is used elsewhere (T2, T7, T10, ...)

**Comment by CannaCardo** [comment]
- [x] fix silkscreen markings for the Magneto project

**Comment by gkasprow** [comment]
added new DIOT sequencer
